config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'

  get    'signup'  => 'users#new'
 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts, only: [:create, :destroy]

  resources :relationships, only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<p class="alert alert-danger"><%= pluralize(object.errors.count, "error") %>.</p>
	<ul>
	<% object.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<ol class="microposts">
	<% # renders microposts/_micropost.html.erb; feed_itmes is class Micropost %>
	<%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_logged_in_home.html.erb
<div class="row">
	<aside class="col-md-4">
		<section class="user-info">
			<%= render 'shared/user_info' %>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
		<section class="micropost-form">
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>
	<div class="col-md-8">
		<h3>Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>

app/views/shared/_logged_out_home.html.erb
<div class="center jumbotron">
	<h1>Sample</h1>
	<h2 class="weak">Practice makes perfect.</h2>
	<p><%= link_to "Sign up.", signup_path, class: "btn btn-lg btn-primary" %></p>
</div>
<p class="weak">A <%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org' %> application.</p>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { multipart: true }) do |f| %>
<% # f.object refers to @micropost, since shared/error_messages typically uses @user. %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
<%= f.text_area :content, placeholder: "Compose new micropost…" %>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
<% end %>

<script>
document.getElementById('micropost_picture').addEventListener('change', function () {
		var pictureSize = this.files[0].size / (1024 * 1024);

		if (pictureSize > 5) {
			var message = 'The maximum file size is 5MB. Please choose a smaller file.',
					p = document.createElement('p');

			p.setAttribute('class', 'alert alert-danger');
			p.textContent = message;

			this.parentNode.appendChild(p);
		}
});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="js-following" class="stat"><%= @user.following.count %></strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="js-followers" class="stat"><%= @user.followers.count %></strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<p><%= link_to "view profile", current_user %></p>
<p><%= pluralize(current_user.microposts.count, "micropost") %></p>